### ISSUE TITLE
Can't install in python 2.7

### ISSUE THREAD

**Issue by mlissner** [brandonhamilton/updown-python#2]
You have to manually install requests first.

```
↪ mkvirtualenv updown
New python executable in /home/mlissner/.virtualenvs/updown/bin/python
Installing setuptools, pip, wheel...
done.
virtualenvwrapper.user_scripts creating /home/mlissner/.virtualenvs/updown/bin/predeactivate
virtualenvwrapper.user_scripts creating /home/mlissner/.virtualenvs/updown/bin/postdeactivate
virtualenvwrapper.user_scripts creating /home/mlissner/.virtualenvs/updown/bin/preactivate
virtualenvwrapper.user_scripts creating /home/mlissner/.virtualenvs/updown/bin/postactivate
virtualenvwrapper.user_scripts creating /home/mlissner/.virtualenvs/updown/bin/get_env_details
(updown) 11:19:00::mlissner@gabbro::~ 
↪ pip install updown
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting updown
  Downloading updown-0.1.0.tar.gz (2.5 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/mlissner/.virtualenvs/updown/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-RPgR52/updown/setup.py'"'"'; __file__='"'"'/tmp/pip-install-RPgR52/updown/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-z2F86s
         cwd: /tmp/pip-install-RPgR52/updown/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-RPgR52/updown/setup.py", line 32, in <module>
        import updown
      File "updown/__init__.py", line 31, in <module>
        import requests
    ImportError: No module named requests
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
(updown) 11:19:04::mlissner@gabbro::~ 
↪ pip install requests
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting requests
  Downloading requests-2.24.0-py2.py3-none-any.whl (61 kB)
     |████████████████████████████████| 61 kB 421 kB/s 
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Using cached urllib3-1.25.9-py2.py3-none-any.whl (126 kB)
Collecting certifi>=2017.4.17
  Downloading certifi-2020.6.20-py2.py3-none-any.whl (156 kB)
     |████████████████████████████████| 156 kB 20.9 MB/s 
Collecting chardet<4,>=3.0.2
  Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting idna<3,>=2.5
  Using cached idna-2.9-py2.py3-none-any.whl (58 kB)
Installing collected packages: urllib3, certifi, chardet, idna, requests
Successfully installed certifi-2020.6.20 chardet-3.0.4 idna-2.9 requests-2.24.0 urllib3-1.25.9
(updown) 11:19:19::mlissner@gabbro::~ 
↪ pip install updown
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting updown
  Using cached updown-0.1.0.tar.gz (2.5 kB)
Requirement already satisfied: requests[security] in ./.virtualenvs/updown/lib/python2.7/site-packages (from updown) (2.24.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in ./.virtualenvs/updown/lib/python2.7/site-packages (from requests[security]->updown) (1.25.9)
Requirement already satisfied: certifi>=2017.4.17 in ./.virtualenvs/updown/lib/python2.7/site-packages (from requests[security]->updown) (2020.6.20)
Requirement already satisfied: chardet<4,>=3.0.2 in ./.virtualenvs/updown/lib/python2.7/site-packages (from requests[security]->updown) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in ./.virtualenvs/updown/lib/python2.7/site-packages (from requests[security]->updown) (2.9)
Collecting cryptography>=1.3.4; extra == "security"
  Downloading cryptography-2.9.2-cp27-cp27mu-manylinux2010_x86_64.whl (2.7 MB)
     |████████████████████████████████| 2.7 MB 9.4 MB/s 
Collecting pyOpenSSL>=0.14; extra == "security"
  Downloading pyOpenSSL-19.1.0-py2.py3-none-any.whl (53 kB)
     |████████████████████████████████| 53 kB 3.2 MB/s 
Collecting enum34; python_version < "3"
  Downloading enum34-1.1.10-py2-none-any.whl (11 kB)
Collecting six>=1.4.1
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting ipaddress; python_version < "3"
  Using cached ipaddress-1.0.23-py2.py3-none-any.whl (18 kB)
Collecting cffi!=1.11.3,>=1.8
  Downloading cffi-1.14.0-cp27-cp27mu-manylinux1_x86_64.whl (387 kB)
     |████████████████████████████████| 387 kB 73.1 MB/s 
Collecting pycparser
  Downloading pycparser-2.20-py2.py3-none-any.whl (112 kB)
     |████████████████████████████████| 112 kB 49.9 MB/s 
Building wheels for collected packages: updown
  Building wheel for updown (setup.py) ... done
  Created wheel for updown: filename=updown-0.1.0-py2-none-any.whl size=2807 sha256=05df66826694ea2287345c6eb6dfda3c0df8e94c5506ca303164242fdf5a918a
  Stored in directory: /home/mlissner/.cache/pip/wheels/8f/60/7b/e641f0ef44f07b325f4bef7fa08bbe72e661a5d98bc9a87af3
Successfully built updown
Installing collected packages: updown, enum34, six, ipaddress, pycparser, cffi, cryptography, pyOpenSSL
Successfully installed cffi-1.14.0 cryptography-2.9.2 enum34-1.1.10 ipaddress-1.0.23 pyOpenSSL-19.1.0 pycparser-2.20 six-1.15.0 updown-0.1.0
```

**Comment by brandonhamilton** [comment]
Fixed in #5
